apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Kustomization
      name: vote
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kustomize/vote/overlays/staging
  - target:
      kind: ImageUpdateAutomation
      name: vote
    patch: |-
      - op: replace
        path: /spec/update/path
        value: ./kustomize/vote/overlays/staging
  - target:
      kind: Kustomization
      name: redis
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kustomize/redis/overlays/staging
  - target:
      kind: Kustomization
      name: worker
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kustomize/worker/overlays/staging
