apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: instavote
spec:
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  path: ./manifests/monitoring/monitoring-config
  targetNamespace: instavote
  dependsOn:
    - name: kube-prometheus-stack
  interval: 1h
  prune: true
