apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: instavote
spec:
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  path: ./kustomize/redis
  targetNamespace: instavote
  interval: 1m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: redis
      namespace: instavote
