apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result
  namespace: instavote
spec:
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: instavote-deploy
      chart: ./helm/charts/result
      reconcileStrategy: Revision
  targetNamespace: instavote
  interval: 1m
