apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  sourceRef:
    kind: GitRepository
    name: instavote
  path: ./kustomize/vote
  targetNamespace: instavote
  dependsOn:
    - name: redis
  interval: 1m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vote
      namespace: instavote
