apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker
  namespace: instavote
spec:
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  path: ./kustomize/worker
  targetNamespace: instavote
  interval: 1m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: worker
      namespace: instavote
